# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binary_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='binary_data.proto',
  package='binaryData',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62inary_data.proto\x12\nbinaryData\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\x08\x42lobSpec\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x13\n\x0b\x63hunk_count\x18\x02 \x01(\x05\"[\n\x08\x42lobInfo\x12\x1e\n\x02id\x18\x01 \x01(\x0b\x32\x12.binaryData.BlobId\x12/\n\x0bvalid_until\x18\x02 \x01(\x0b\x32\x1a.binaryData.ExpirationTime\"\x1c\n\x05\x45rror\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\":\n\x0e\x45xpirationTime\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x14\n\x06\x42lobId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x94\x01\n\x08Response\x12\"\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x11.binaryData.ErrorH\x00\x12\x31\n\x0bvalid_until\x18\x02 \x01(\x0b\x32\x1a.binaryData.ExpirationTimeH\x00\x12)\n\tblob_info\x18\x03 \x01(\x0b\x32\x14.binaryData.BlobInfoH\x00\x42\x06\n\x04type2B\n\x06Upload\x12\x38\n\nCreateBlob\x12\x14.binaryData.BlobSpec\x1a\x14.binaryData.Response2N\n\nFileServer\x12@\n\x12ValidateFileServer\x12\x14.binaryData.BlobSpec\x1a\x14.binaryData.Responseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_BLOBSPEC = _descriptor.Descriptor(
  name='BlobSpec',
  full_name='binaryData.BlobSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='binaryData.BlobSpec.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_count', full_name='binaryData.BlobSpec.chunk_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=111,
)


_BLOBINFO = _descriptor.Descriptor(
  name='BlobInfo',
  full_name='binaryData.BlobInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='binaryData.BlobInfo.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_until', full_name='binaryData.BlobInfo.valid_until', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=204,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='binaryData.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='binaryData.Error.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=234,
)


_EXPIRATIONTIME = _descriptor.Descriptor(
  name='ExpirationTime',
  full_name='binaryData.ExpirationTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='binaryData.ExpirationTime.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=294,
)


_BLOBID = _descriptor.Descriptor(
  name='BlobId',
  full_name='binaryData.BlobId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='binaryData.BlobId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=316,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='binaryData.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='binaryData.Response.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_until', full_name='binaryData.Response.valid_until', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blob_info', full_name='binaryData.Response.blob_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='binaryData.Response.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=319,
  serialized_end=467,
)

_BLOBINFO.fields_by_name['id'].message_type = _BLOBID
_BLOBINFO.fields_by_name['valid_until'].message_type = _EXPIRATIONTIME
_EXPIRATIONTIME.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RESPONSE.fields_by_name['error'].message_type = _ERROR
_RESPONSE.fields_by_name['valid_until'].message_type = _EXPIRATIONTIME
_RESPONSE.fields_by_name['blob_info'].message_type = _BLOBINFO
_RESPONSE.oneofs_by_name['type'].fields.append(
  _RESPONSE.fields_by_name['error'])
_RESPONSE.fields_by_name['error'].containing_oneof = _RESPONSE.oneofs_by_name['type']
_RESPONSE.oneofs_by_name['type'].fields.append(
  _RESPONSE.fields_by_name['valid_until'])
_RESPONSE.fields_by_name['valid_until'].containing_oneof = _RESPONSE.oneofs_by_name['type']
_RESPONSE.oneofs_by_name['type'].fields.append(
  _RESPONSE.fields_by_name['blob_info'])
_RESPONSE.fields_by_name['blob_info'].containing_oneof = _RESPONSE.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['BlobSpec'] = _BLOBSPEC
DESCRIPTOR.message_types_by_name['BlobInfo'] = _BLOBINFO
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['ExpirationTime'] = _EXPIRATIONTIME
DESCRIPTOR.message_types_by_name['BlobId'] = _BLOBID
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlobSpec = _reflection.GeneratedProtocolMessageType('BlobSpec', (_message.Message,), dict(
  DESCRIPTOR = _BLOBSPEC,
  __module__ = 'binary_data_pb2'
  # @@protoc_insertion_point(class_scope:binaryData.BlobSpec)
  ))
_sym_db.RegisterMessage(BlobSpec)

BlobInfo = _reflection.GeneratedProtocolMessageType('BlobInfo', (_message.Message,), dict(
  DESCRIPTOR = _BLOBINFO,
  __module__ = 'binary_data_pb2'
  # @@protoc_insertion_point(class_scope:binaryData.BlobInfo)
  ))
_sym_db.RegisterMessage(BlobInfo)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'binary_data_pb2'
  # @@protoc_insertion_point(class_scope:binaryData.Error)
  ))
_sym_db.RegisterMessage(Error)

ExpirationTime = _reflection.GeneratedProtocolMessageType('ExpirationTime', (_message.Message,), dict(
  DESCRIPTOR = _EXPIRATIONTIME,
  __module__ = 'binary_data_pb2'
  # @@protoc_insertion_point(class_scope:binaryData.ExpirationTime)
  ))
_sym_db.RegisterMessage(ExpirationTime)

BlobId = _reflection.GeneratedProtocolMessageType('BlobId', (_message.Message,), dict(
  DESCRIPTOR = _BLOBID,
  __module__ = 'binary_data_pb2'
  # @@protoc_insertion_point(class_scope:binaryData.BlobId)
  ))
_sym_db.RegisterMessage(BlobId)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'binary_data_pb2'
  # @@protoc_insertion_point(class_scope:binaryData.Response)
  ))
_sym_db.RegisterMessage(Response)



_UPLOAD = _descriptor.ServiceDescriptor(
  name='Upload',
  full_name='binaryData.Upload',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=469,
  serialized_end=535,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateBlob',
    full_name='binaryData.Upload.CreateBlob',
    index=0,
    containing_service=None,
    input_type=_BLOBSPEC,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOAD)

DESCRIPTOR.services_by_name['Upload'] = _UPLOAD


_FILESERVER = _descriptor.ServiceDescriptor(
  name='FileServer',
  full_name='binaryData.FileServer',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=537,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='ValidateFileServer',
    full_name='binaryData.FileServer.ValidateFileServer',
    index=0,
    containing_service=None,
    input_type=_BLOBSPEC,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVER)

DESCRIPTOR.services_by_name['FileServer'] = _FILESERVER

# @@protoc_insertion_point(module_scope)
